schema:
  - ./src/schema.ts:
      require: ts-node/register
extensions:
  codegen:
    generates:
      ./src/resolver-types.ts:
        plugins:
          - typescript
          - typescript-resolvers
