packages:
  - packages/*
  - packages/plugins/*
  - packages/client/*
  - packages/event-target/*
  - examples/**/*
  - '!examples/bun/*'
  - '!examples/bun-yoga-ws/*'
  - '!examples/deno/*'
  - '!examples/gcp-gcloud-run'
  - '!examples/gcp-functions'
  - '!examples/firebase/*'
  - '!examples/**/dist'
  - '!packages/**/dist'
  - benchmark
  - website
  - e2e
