packages:
  - packages/*
  - packages/plugins/*
  - packages/client/*
  - packages/event-target/*
  - examples/**/*
  - '!examples/**/dist'
  - '!examples/nestjs-apollo-federation-compatibility'
  - '!packages/**/dist'
  - benchmark
  - website
  - e2e
