import Head from 'next/head'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>GraphQL Yoga</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>

        <p className={styles.description}>
          Edit the GraphQL Schema
          <a href="/api/graphql" target="_blank">
            <code className={styles.code}>pages/api/graphql.js</code>
          </a>
        </p>

        <div className={styles.grid}>
          <a href="https://nextjs.org/docs" className={styles.card}>
            <h2>Learn &rarr;</h2>
            <p>Learn about Next.js</p>
          </a>
          <a href="https://graphql-yoga.vercel.app" className={styles.card}>
            <h2>Learn &rarr;</h2>
            <p>Learn about GraphQL Yoga</p>
          </a>
        </div>
      </main>
    </div>
  )
}
