export default {
  schema: 'GraphQL Schema',
  graphiql: 'GraphiQL',
  context: 'GraphQL Context',
  'error-masking': '',
  'execution-cancellation': '',
  introspection: '',
  subscriptions: '',
  'file-uploads': '',
  'defer-stream': 'Defer and Stream',
  'request-batching': '',
  cors: '',
  'csrf-prevention': '',
  'parsing-and-validation-caching': '',
  'response-caching': '',
  'persisted-operations': '',
  'automatic-persisted-queries': '',
  'logging-and-debugging': '',
  'health-check': '',
  'sofa-api': 'REST API',
  cookies: '',
  'apollo-federation': '',
  testing: '',
  jwt: '',
  'landing-page': '',
  'request-customization': '',
  'explicit-resource-management': '',
  'envelop-plugins': 'Custom Plugins',
};
