export default {
  index: 'Introduction',
  '01-project-setup': 'Project Setup',
  '02-getting-started': 'Getting Started',
  '03-graphql-server': 'GraphQL Server',
  '04-a-simple-query': 'A Simple Query',
  '05-a-simple-mutation': 'A Simple Mutation',
  '06-adding-a-database': 'Adding a Database',
  '07-connecting-server-and-database': 'Connecting Server and Database',
  '08-graph-relations': 'Graph Relations',
  '09-set-up-graphql-code-generator': 'Set up GraphQL Code Generator',
  '10-error-handling': 'Error Handling',
  '11-filtering-and-pagination': 'Filtering and Pagination',
  '12-summary': 'Summary',
};
