# https://github.com/microsoft/playwright/issues/7249
name: Install Playwright Binaries
description: Install Playwright browsers with cache
inputs:
  working-directory:
    description: Where to install Playwright
    default: ./
  browsers:
    description: Browsers to install
    default: chromium
outputs:
  version:
    description: Installed version of Playwright
    value: ${{ steps.version.outputs.version }}
  cache-hit:
    description: Whether cache for Playwright was found
    value: ${{ steps.cache.outputs.cache-hit }}
runs:
  using: composite
  steps:
    - name: Get Playwright version
      uses: actions/github-script@v7
      id: version
      with:
        script: |
          // https://github.com/actions/toolkit/issues/1624
          // const workingDirectory = core.getInput("working-directory");
          const workingDirectory = "${{ inputs.working-directory }}";
          console.debug("Specified working directory:", workingDirectory);
          if (workingDirectory) process.chdir(workingDirectory);
          console.debug("Actual working directory:", process.cwd());
          let version = "";
          try {
            version = require("playwright/package.json").version;
          } catch (error) {
            console.log(error.message);
          }
          console.debug("Version:", version);
          if (version) {
            core.exportVariable("PLAYWRIGHT_VERSION", version);
            core.setOutput("version", version);
          } else core.setFailed("Couldn't get Playwright version");

    - name: Cache Playwright
      id: cache
      uses: actions/cache@v4
      with:
        path: ~/.cache/ms-playwright
        key: playwright-${{ env.PLAYWRIGHT_VERSION }}

    - name: Install Playwright Browsers
      shell: bash
      if: steps.cache.outputs.cache-hit != 'true'
      working-directory: ${{ inputs.working-directory }}
      run: npx playwright install ${{ inputs.browsers }}
