name = "graphql-yoga-example"
type = "javascript"

account_id = ""
workers_dev = true

compatibility_date = "2021-11-15"
compatibility_flags = ["streams_enable_constructors"]

[build]
command = "npm run build"

[build.upload]
format = "modules"
dir = "dist"
main = "./index.mjs"